### ISSUE TITLE
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/GitBlame#8]
```bash
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
Caused by: ApplicationException: Can't find msysgit installed on the system.
   at GitBlame.Models.GitWrapper.GetGitPath()
   at GitBlame.Models.GitWrapper.<>c__DisplayClass12.<GetBlameOutput>b__7()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by bgrainger** [comment]
11 months old; assuming fixed.
